apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-live-update
  labels:
    app.kubernetes.io/name: fbapp-live-update
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fbapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fbapp-live-update
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: fbapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fbapp-live-update
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: fbapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "live-update"
    spec:
      containers:
      - name: fbapp-live-update
        image: localhost:32000/fbapp-live-update:registry
        imagePullPolicy: Always
        env:
        - name: Api__Token
          valueFrom:
            secretKeyRef:
              name: fbapp
              key: footballDataToken
