apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: fbapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: fbapp
  replicas: 1
  serviceName: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: fbapp
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.6
        args:
        - --bind_ip
        - 0.0.0.0
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 27017
