name: fbapp

services:
  - name: fbapp-ui
    executable: node
    workingDirectory: fbapp-ui
    args: node_modules/yarn/bin/yarn.js quasar dev
    bindings:
      - port: 8080
        protocol: https

  - name: fbapp-proxy
    project: fbapp-proxy/FbApp.Proxy.fsproj
    bindings:
      - port: 8090
        protocol: https

  - name: fbapp-auth
    project: fbapp-auth-service/FbApp.Auth.fsproj
    bindings:
      - port: 7002
        protocol: http

  - name: fbapp-web-service
    project: fbapp-web-service/FbApp.Web.fsproj
    bindings:
      - port: 7001
        protocol: http

  - name: eventstore
    image: eventstore/eventstore
    args: '--insecure --run-projections=All --enable-atom-pub-over-http'
    bindings:
      - name: http
        port: 2113

  - name: mongodb
    image: bitnami/mongodb
    bindings:
      - port: 27017

  - name: postgres
    image: postgres
    args: postgres -N 1000
    bindings:
      - port: 5432
        protocol: tcp
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: fbapp
    volumes:
      - source: ./.postgres
        target: /var/lib/postgresql/data
