name: fbapp

extensions:
  - name: dapr

ingress:
  - name: ingress
    bindings:
      - port: 8090
    rules:
      - path: /.well-known
        preservePath: true
        service: fbapp-proxy
      - path: /api
        preservePath: true
        service: fbapp-proxy
      - path: /connect
        preservePath: true
        service: fbapp-proxy
      - path: /
        service: fbapp-ui

services:
  - name: fbapp-ui
    executable: node
    workingDirectory: fbapp-ui
    args: ./node_modules/.bin/vite
    bindings:
      - port: 3000
        protocol: http

  - name: fbapp-proxy
    project: fbapp-proxy/FbApp.Proxy.fsproj

  - name: fbapp-auth
    project: fbapp-auth-service/FbApp.Auth.fsproj
    bindings:
      - connectionString: http://${host}:${port}

  - name: fbapp-competitions
    project: fbapp-competitions-service/FbApp.Competitions.fsproj

  - name: fbapp-web-service
    project: fbapp-web-service/FbApp.Web.fsproj

  - name: eventstore
    image: eventstore/eventstore
    args: --insecure --run-projections=All
    bindings:
      - containerPort: 2113
        protocol: esdb
        connectionString: ${protocol}://${host}:${port}?tls=false

  - name: mongodb
    image: bitnami/mongodb
    bindings:
      - containerPort: 27017
        protocol: mongodb
        connectionString: ${protocol}://${host}:${port}

  - name: postgres
    image: postgres
    args: postgres -N 1000
    bindings:
      - containerPort: 5432
        protocol: tcp
        connectionString: Host=${host};Port=${port};Database=${env:POSTGRES_DB};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: fbapp
      - name: POSTGRES_INITDB_ARGS
        value: --auth-host=md5
      - name: POSTGRES_HOST_AUTH_METHOD
        value: md5
    volumes:
      - source: ./.postgres
        target: /var/lib/postgresql/data
