FROM node:lts-alpine AS build
WORKDIR /app
RUN wget -O - 'https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz' | gunzip -c >/usr/local/bin/elm
RUN chmod +x /usr/local/bin/elm
COPY package*.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
EXPOSE 5173
CMD ["yarn", "dev"]
