k8s_yaml('./kubernetes/deployment.yaml')
k8s_yaml('./kubernetes/service.yaml')

docker_build('fbapp-web-image', '.',
    dockerfile='Dockerfile.Development',
    live_update=[
        fall_back_on(['package.json', 'yarn.lock']),
        sync('.', '/app')
    ]
)

k8s_resource('fbapp-web', labels=['fbapp-web'])
