load('ext://helm_remote', 'helm_remote')

helm_remote(
    'postgresql',
    release_name='fbapp-auth-database',
    repo_name='bitnami',
    repo_url='https://charts.bitnami.com/bitnami',
    set='auth.database=fbapp_auth,auth.username=user,auth.password=password,auth.postgresPassword=postgres'
)

k8s_resource('fbapp-auth-database-postgresql', port_forwards='5432:5432', labels=['fbapp-auth'])
