{{- $fullName := include "fbapp.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $fullName "auth" }}
  labels:
    {{- include "fbapp.labels" . | nindent 4 }}
    app: {{ printf "%s-%s" $fullName "auth" }}
spec:
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fbapp.selectorLabels" . | nindent 6 }}
      app: {{ printf "%s-%s" $fullName "auth" }}
  template:
    metadata:
      {{- with .Values.auth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fbapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.auth.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ printf "%s-%s" $fullName "auth" }}
    spec:
      {{- with .Values.auth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fbapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.auth.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.auth.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.auth.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.auth.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.auth.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
          {{- with .Values.auth.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.auth.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.auth.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
