{{- $fullName := include "fbapp.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $fullName "auth" }}
  labels:
    {{- include "fbapp.labels" . | nindent 4 }}
    app: {{ printf "%s-%s" $fullName "auth" }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fbapp.selectorLabels" . | nindent 4 }}
    app: {{ printf "%s-%s" $fullName "auth" }}
