apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: fbapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: cache
      app.kubernetes.io/part-of: fbapp
  replicas: 1
  serviceName: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: fbapp
    spec:
      containers:
      - name: redis
        image: redis:6.2.4-alpine
        imagePullPolicy: Always
        args:
        - --appendonly
        - 'yes'
        ports:
        - containerPort: 6379
