kind: Service
apiVersion: v1
metadata:
  name: fbapp-eventstore
  labels:
    app: fbapp-eventstore
spec:
  ports:
  - port: 2113
    targetPort: 2113
  selector:
    app: fbapp-eventstore
  type: ClusterIP
