load('ext://restart_process', 'docker_build_with_restart')

local_resource(
    'fbapp-proxy-build',
    'dotnet publish -c Release -o out',
    deps=['fbapp-proxy'],
    ignore=['obj'],
    labels=['fbapp-proxy']
)

docker_build_with_restart(
    'fbapp-proxy-image',
    'out',
    entrypoint=['dotnet', 'FbApp.Proxy.dll'],
    dockerfile='Dockerfile.Development',
    live_update=[
        sync('out', '/app/out')
    ]
)

k8s_yaml('./kubernetes/deployment.yaml')
k8s_yaml('./kubernetes/service.yaml')

k8s_resource('fbapp-proxy', resource_deps=['fbapp-proxy-build'], labels=['fbapp-proxy'])
