apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-ui
  labels:
    app.kubernetes.io/name: fbapp-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fbapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fbapp-ui
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: fbapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fbapp-ui
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: fbapp
    spec:
      containers:
      - name: fbapp-ui
        image: localhost:32000/fbapp-ui:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 80
