apiVersion: v1
kind: Service
metadata:
  name: fbapp-ui
  labels:
    app.kubernetes.io/name: fbapp-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fbapp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: fbapp-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fbapp
