apiVersion: v1
kind: Service
metadata:
  name: eventstore
  labels:
    app.kubernetes.io/name: eventstore
    app.kubernetes.io/component: eventstore
    app.kubernetes.io/part-of: fbapp
spec:
  ports:
  - port: 2113
    targetPort: 2113
  selector:
    app.kubernetes.io/name: eventstore
    app.kubernetes.io/component: eventstore
    app.kubernetes.io/part-of: fbapp
