apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore
  labels:
    app.kubernetes.io/name: eventstore
    app.kubernetes.io/component: eventstore
    app.kubernetes.io/part-of: fbapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eventstore
      app.kubernetes.io/component: eventstore
      app.kubernetes.io/part-of: fbapp
  replicas: 1
  serviceName: eventstore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventstore
        app.kubernetes.io/component: eventstore
        app.kubernetes.io/part-of: fbapp
    spec:
      containers:
      - name: eventstore
        image: eventstore/eventstore:21.2.0-bionic
        args:
        - --insecure
        - --run-projections=All
        ports:
        - containerPort: 2113
