apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-proxy
spec:
  selector:
    matchLabels:
      app: fbapp-proxy
  replicas: 1
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "fbapp-proxy"
        dapr.io/log-level: "debug"
      labels:
        app: fbapp-proxy
    spec:
      containers:
      - name: fbapp-proxy
        image: fbapp-proxy-image
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__fbapp-auth
          value: http://fbapp-auth
