load('ext://helm_remote', 'helm_remote')

helm_remote('redis',
    release_name='fbapp-api-redis',
    repo_name='bitnami',
    repo_url='https://charts.bitnami.com/bitnami',
    set=[
        "architecture=standalone",
        "auth.enabled=false"
    ]
)

k8s_resource(new_name='fbapp-api-redis-resources', labels=['fbapp-api'], objects=[
    'fbapp-api-redis:networkpolicy',
    'fbapp-api-redis-configuration:configmap',
    'fbapp-api-redis-health:configmap',
    'fbapp-api-redis-master:poddisruptionbudget',
    'fbapp-api-redis-master:serviceaccount',
    'fbapp-api-redis-scripts:configmap',
    'fbapp-state:component'
])

k8s_resource('fbapp-api-redis-master', labels=['fbapp-api'], resource_deps=[
    'fbapp-api-redis-resources'
])
