apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-web
  labels:
    app: fbapp-web
spec:
  selector:
    matchLabels:
      app: fbapp-web
  template:
    metadata:
      labels:
        app: fbapp-web
    spec:
      containers:
        - name: fbapp-web
          image: fbapp-web-image
          ports:
            - containerPort: 5173
