{{- $fullName := include "fbapp.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $fullName "proxy" }}
  labels:
    {{- include "fbapp.labels" . | nindent 4 }}
    app: {{ printf "%s-%s" $fullName "proxy" }}
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fbapp.selectorLabels" . | nindent 6 }}
      app: {{ printf "%s-%s" $fullName "proxy" }}
  template:
    metadata:
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fbapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.proxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ printf "%s-%s" $fullName "proxy" }}
    spec:
      {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fbapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ printf "%s-%s" $fullName "proxy" }}
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.proxy.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.proxy.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          {{- with .Values.proxy.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.proxy.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
