apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-auth
spec:
  selector:
    matchLabels:
      app: fbapp-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: fbapp-auth
    spec:
      containers:
      - name: fbapp-auth
        image: fbapp-auth-image
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__postgres
          value: Host=fbapp-auth-database-postgresql;Port=5432;Database=fbapp_auth;Username=user;Password=password
