apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-api
spec:
  selector:
    matchLabels:
      app: fbapp-api
  template:
    metadata:
      labels:
        app: fbapp-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "fbapp-api"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: fbapp-api
        image: localhost:32000/fbapp-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__mongodb
          valueFrom:
            configMapKeyRef:
              name: fbapp-api-config
              key: MongoDbUri
        - name: Authentication__FootballDataToken
          valueFrom:
            configMapKeyRef:
              name: fbapp-api-config
              key: FootballDataToken
        - name: EventStore__Uri
          valueFrom:
            configMapKeyRef:
              name: fbapp-api-config
              key: EventStoreUri
