load('ext://helm_remote', 'helm_remote')

helm_remote('mongodb',
    release_name='fbapp-api-database',
    repo_name='bitnami',
    repo_url='https://charts.bitnami.com/bitnami',
    set=[
        "architecture=standalone",
        "auth.usernames[0]=user",
        "auth.passwords[0]=password",
        "auth.databases[0]=fbapp",
        "auth.rootPassword=root"
    ]
)

k8s_resource(new_name='fbapp-api-database-resources', labels=['fbapp-api'], objects=[
    'fbapp-api-database-mongodb:networkpolicy',
    'fbapp-api-database-mongodb:persistentvolumeclaim',
    'fbapp-api-database-mongodb:poddisruptionbudget',
    'fbapp-api-database-mongodb:secret',
    'fbapp-api-database-mongodb:serviceaccount',
    'fbapp-api-database-mongodb-common-scripts:configmap'
])

k8s_resource('fbapp-api-database-mongodb', labels=['fbapp-api'], port_forwards='27017:27017', resource_deps=[
    'fbapp-api-database-resources'
])
