apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-auth
spec:
  selector:
    matchLabels:
      app: fbapp-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: fbapp-auth
    spec:
      containers:
      - name: fbapp-auth
        image: localhost:32000/fbapp-auth:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__postgres
          value: Host=fbapp-auth-database-postgresql;Port=5432;Database=fbapp_auth;Username=user;Password=password
        - name: Authorization__DefaultAdmin
          valueFrom:
            configMapKeyRef:
              name: fbapp-auth-config
              key: DefaultAdmin
        - name: Google__Authentication__ClientId
          valueFrom:
            configMapKeyRef:
              name: fbapp-auth-config
              key: GoogleClientId
        - name: Google__Authentication__ClientSecret
          valueFrom:
            configMapKeyRef:
              name: fbapp-auth-config
              key: GoogleClientSecret
        - name: Authentication__RedirectUris__0
          valueFrom:
            configMapKeyRef:
              name: fbapp-auth-config
              key: RedirectUri
