apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-web
  labels:
    app: fbapp-web
spec:
  selector:
    matchLabels:
      app: fbapp-web
  template:
    metadata:
      labels:
        app: fbapp-web
    spec:
      containers:
      - name: fbapp-web
        image: localhost:32000/fbapp-web:latest
        ports:
        - containerPort: 80
