apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: fbapp
patchesStrategicMerge: []
# - eventstore-service.yaml
# - eventstore-statefulset.yaml
# - mongo-statefulset.yaml
# - redis-statefulset.yaml
resources:
- ingress.yaml
