apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbapp-proxy
spec:
  selector:
    matchLabels:
      app: fbapp-proxy
  replicas: 1
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "fbapp-proxy"
        dapr.io/app-port: "80"
      labels:
        app: fbapp-proxy
    spec:
      containers:
      - name: fbapp-proxy
        image: localhost:32000/fbapp-proxy:latest
        ports:
        - containerPort: 80
        env:
        - name: CONNECTIONSTRINGS__AUTHCLUSTER
          value: http://fbapp-auth
